export const cuisineList = [
  "Biryani",
  "Butter Chicken",
  "Chole Bhature",
  "Dosa",
  "Idli",
  "Kebabs",
  "Masala Dosa",
  "Paneer Tikka",
  "Pani Puri",
  "Rogan Josh",
  "Samosa",
  "Tandoori Chicken",
  "Vada Pav",
  "Palak Paneer",
  "Aloo Gobi",
  "Dal Makhani",
  "Hyderabadi Biryani",
  "Pav Bhaji",
  "Chicken Curry",
  "Fish Curry",
  "Gulab Jamun",
  "Jalebi",
  "Rasgulla",
  "Malai Kofta",
  "Lassi"
    ];